openapi: 3.0.2
info:
  description: A Web Application that helps you remember where things cost less
  version: 1.0.0
  title: Shopping Saver
  contact:
    email: biral.mattia@gmail.com
  license:
    name: GPL-3.0
    url: https://www.gnu.org/licenses/gpl-3.0.en.html
servers:
  - url: https://shoppingsaver.my.to/api/
tags:
  - name: feedbacks
    description: Handles form feedbacks
  - name: temp-users
    description: Handles registration and confirmation requests
  - name: auth
    description: Handles user authentication
  - name: settings
    description: Handles user settings
  - name: categories
    description: Handles categories
  - name: brands
    description: Handles brands
  - name: supermarkets
    description: Handles supermarkets
  - name: products
    description: Handles products
components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: shoppingsaver-auth
  schemas:
    username:
      type: string
      example: Pyrix25633
      minLength: 3
      maxLength: 32
    email:
      type: string
      format: email
      example: name.surname@domain.com
    password:
      type: string
      example: passwd1234@
      minLength: 8
    token:
      type: string
      example: 4b135f35634c8f34258551d907f179a1d2847a2e6a55f54d399b3a0928294a5f30c842bf2ebcf2aad96769d6c3e50f216d386c15b3caebc07ec72696577a1d01
      minLength: 128
      maxLength: 128
    tfaKey:
      type: string
      example: NUZSQS3CNRMGYJBJNATFI2BIJ4QUGULDKNKDS6CGJ5XWC4B4KIRQ
      minLength: 52
      maxLength: 52
    tfaCode:
      type: integer
      minimum: 100000
      maximum: 999999
      example: 190347
    id:
      type: integer
      example: 26
      minimum: 1
    customization:
      type: object
      properties:
        compactMode:
          type: boolean
          example: false
        condensedFont:
          type: boolean
          example: false
        aurebeshFont:
          type: boolean
          example: false
        sharpMode:
          type: boolean
          example: false
      required:
        - compactMode
        - condensedFont
        - aurebeshFont
        - sharpMode
    sessionDuration:
      type: integer
      example: 14
      minimum: 5
      maximum: 90
    base64Image:
      type: string
      example: "data:image/svg+xml;base64,czY0OGI0bmcxNjViMjYrc3NjNDF2ZjJhKzR3ZjF2Y2EyYSsx..."
    name:
      type: string
      minLength: 3
      maxLength: 32
    quantity:
      type: integer
      example: 500
      minimum: 1
    unitOfMeasurement:
      type: string
      enum:
        - PIECES
        - GRAMS
        - MILLILITER
    price:
      type: number
      example: 12.50
      minimum: 0.01
    decimal:
      type: string
      format: decimal
      example: "12.50"
    page:
      type: integer
      example: 2
      minimum: 0
    pages:
      type: integer
      example: 3
      minimum: 1
    orderValue:
      type: object
      additionalProperties:
        type: array
        items:
          oneOf:
            - type: string
              enum:
                - asc
                - desc
            - $ref: "#/components/schemas/orderValue"
    order:
      type: array
      items:
        type: object
        $ref: "#/components/schemas/orderValue"
    filter:
      type: object
      properties:
        name:
          type: string
          example: Hamb
        categoryId:
          $ref: "#/components/schemas/id"
        supermarketId:
          $ref: "#/components/schemas/id"
        priceVisibility:
          type: string
          enum:
            - ALL
            - BEST
      required:
        - priceVisibility
paths:
  /feedbacks/register-username:
    get:
      tags:
        - feedbacks
      summary: Username feedback for the registration form
      description: Returns a user friendly username feedback
      operationId: feedbacks/register-username
      parameters:
        - in: query
          name: username
          schema:
            $ref: "#/components/schemas/username"
          description: The username, it can be invalid
          required: true
      responses:
        "200":
          description: Username feedback
          content:
            application/json:
              schema:
                type: object
                properties:
                  feedback:
                    type: string
                    example: Valid Username
  /feedbacks/register-email:
    get:
      tags:
        - feedbacks
      summary: Email feedback for the registration form
      description: Returns a user friendly email feedback
      operationId: feedbacks/register-email
      parameters:
        - in: query
          name: email
          schema:
            $ref: "#/components/schemas/email"
          description: The email, it can be invalid
          required: true
      responses:
        "200":
          description: Email feedback
          content:
            application/json:
              schema:
                type: object
                properties:
                  feedback:
                    type: string
                    example: Valid Email
  /feedbacks/confirm-username:
    get:
      tags:
        - feedbacks
      summary: Username feedback for the confirmation form
      description: Returns a user friendly username feedback
      operationId: feedbacks/confirm-username
      parameters:
        - in: query
          name: username
          schema:
            $ref: "#/components/schemas/username"
          description: The username
          required: true
      responses:
        "200":
          description: Username feedback
          content:
            application/json:
              schema:
                type: object
                properties:
                  feedback:
                    type: string
                    example: Valid Username
        "400":
          description: Bad Request
  /feedbacks/login-username:
    get:
      tags:
        - feedbacks
      summary: Username feedback for the login form
      description: Returns a user friendly username feedback
      operationId: feedbacks/login-username
      parameters:
        - in: query
          name: username
          schema:
            $ref: "#/components/schemas/username"
          description: The username
          required: true
      responses:
        "200":
          description: Username feedback
          content:
            application/json:
              schema:
                type: object
                properties:
                  feedback:
                    type: string
                    example: Valid Username
        "400":
          description: Bad Request
  /feedbacks/category-name:
    get:
      tags:
        - feedbacks
      summary: Category's name feedback for the category's creation form
      description: Returns a user friendly category's name feedback
      operationId: feedbacks/category-name
      parameters:
        - in: query
          name: name
          schema:
            $ref: "#/components/schemas/name"
          description: The category's name
          required: true
      responses:
        "200":
          description: Category's name feedback
          content:
            application/json:
              schema:
                type: object
                properties:
                  feedback:
                    type: string
                    example: Valid Name
        "400":
          description: Bad Request
  /feedbacks/brand-name:
    get:
      tags:
        - feedbacks
      summary: Brand's name feedback for the brand's creation form
      description: Returns a user friendly brand's name feedback
      operationId: feedbacks/brand-name
      parameters:
        - in: query
          name: name
          schema:
            $ref: "#/components/schemas/name"
          description: The brand's name
          required: true
      responses:
        "200":
          description: Brand's name feedback
          content:
            application/json:
              schema:
                type: object
                properties:
                  feedback:
                    type: string
                    example: Valid Name
        "400":
          description: Bad Request
  /feedbacks/supermarket-name:
    get:
      tags:
        - feedbacks
      summary: Supermarket's name feedback for the supermarket's creation form
      description: Returns a user friendly supermarket's name feedback
      operationId: feedbacks/supermarket-name
      parameters:
        - in: query
          name: name
          schema:
            $ref: "#/components/schemas/name"
          description: The supermarket's name
          required: true
      responses:
        "200":
          description: Supermarket's name feedback
          content:
            application/json:
              schema:
                type: object
                properties:
                  feedback:
                    type: string
                    example: Valid Name
        "400":
          description: Bad Request
  /feedbacks/product-name:
    get:
      tags:
        - feedbacks
      summary: Product's name feedback for the product's creation form
      description: Returns a user friendly product's name feedback
      operationId: feedbacks/product-name
      parameters:
        - in: query
          name: name
          schema:
            $ref: "#/components/schemas/name"
          description: The product's name
          required: true
        - in: query
          name: brandId
          schema:
            $ref: "#/components/schemas/id"
          description: The product's brand id
          required: true
        - in: query
          name: supermarketId
          schema:
            $ref: "#/components/schemas/id"
          description: The product's supermarket id
          required: true
      responses:
        "200":
          description: Category's name feedback
          content:
            application/json:
              schema:
                type: object
                properties:
                  feedback:
                    type: string
                    example: Valid Name
        "400":
          description: Bad Request
  /temp-users:
    post:
      tags:
        - temp-users
      summary: Creates a new temporary user
      description: First step of the registration process
      operationId: temp-users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  $ref: "#/components/schemas/username"
                email:
                  $ref: "#/components/schemas/email"
                password:
                  $ref: "#/components/schemas/password"
              required:
                - username
                - email
                - password
      responses:
        "201":
          description: The first step of the registration succeded
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    $ref: "#/components/schemas/username"
        "400":
          description: Bad Request
        "422":
          description: "Unprocessable Content: temporary user cannot be created because of duplicate username or email"
  /temp-users/{username}/confirm:
    post:
      tags:
        - temp-users
      summary: Confirms a temporary user
      description: Sencond and last step of the registration process
      operationId: temp-users/[username]/confirm
      parameters:
        - in: path
          name: username
          schema:
            $ref: "#/components/schemas/username"
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                verificationCode:
                  type: integer
                  minimum: 100000
                  maximum: 999999
                  example: 190347
              required:
                - verificationCode
      responses:
        "201":
          description: The second step of the registration succeded, user created
          content:
            application/json:
              schema:
                type: object
                properties:
                  userId:
                    type: integer
                    example: 10
        "400":
          description: Bad Request
        "404":
          description: "Not Found: no temporary users found with specified username"
        "422":
          description: "Unprocessable Content: user cannot be created"
  /auth/validate-token:
    get:
      tags:
        - auth
      summary: Used by client to check whether the user needs to log in
      description: Gets a boolean feedback
      operationId: auth/validate-token
      responses:
        "200":
          description: If true the cookie token is valid
          content:
            application/json:
              schema:
                type: object
                properties:
                  valid:
                    type: boolean
  /auth/login:
    post:
      tags:
        - auth
      summary: Logs the user in if 2FA is not needed
      description: Sets the authentication cookie if 2FA is not needed
      operationId: auth/login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  $ref: "#/components/schemas/username"
                password:
                  $ref: "#/components/schemas/password"
              required:
                - username
                - password
      responses:
        "200":
          description: First authentication step succeded, 2FA is needed
          content:
            application/json:
              schema:
                type: object
                properties:
                  tfaToken:
                    $ref: "#/components/schemas/token"
        "204":
          description: Authentication succeded
          headers:
            Set-Cookie:
              schema:
                type: string
                example: >
                  Set-Cookie: shoppingsaver-auth=...; Path=/; SameSite=Strict; Expires=Tue 09 Apr 2024 11:39:56 GMT
              description: Sets authentication cookie
        "400":
          description: Bad Request
        "401":
          description: "Unauthorized: wrong password"
        "404":
          description: "Not Found: no users found with specified username"
  /auth/login-tfa:
    post:
      tags:
        - auth
      summary: Logs the user in
      description: Sets the authentication cookie
      operationId: auth/login-tfa
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                tfaToken:
                  $ref: "#/components/schemas/token"
                tfaCode:
                  $ref: "#/components/schemas/tfaCode"
              required:
                - tfaToken
                - tfaCode
      responses:
        "204":
          description: Authentication succeded
          headers:
            Set-Cookie:
              schema:
                type: string
                example: >
                  Set-Cookie: shoppingsaver-auth=...; Path=/; SameSite=Strict; Expires=Tue 09 Apr 2024 11:39:56 GMT
              description: Sets authentication cookie
        "400":
          description: Bad Request
        "401":
          description: "Unauthorized: wrong tfaCode"
        "404":
          description: "Not Found: no pending 2FA actions found with specified tfaToken"
        "422":
          description: "Unprocessable Content: user disabled 2FA and this step is not needed"
  /auth/tfa/generate-key:
    get:
      tags:
        - auth
      summary: Used by client to generate a new 2FA key
      description: Called when activating 2FA in user settings
      operationId: auth/tfa/generate-key
      responses:
        "200":
          description: New 2FA key and QR
          content:
            application/json:
              schema:
                type: object
                properties:
                  tfaKey:
                    $ref: "#/components/schemas/tfaKey"
                  tfaQr:
                    $ref: "#/components/schemas/base64Image"
        "401":
          description: Unauthorized
  /auth/tfa/validate-code:
    get:
      tags:
        - auth
      summary: Used by the client to verify that the user correctly scanned the QR
      description: Gets a boolean feedbacks
      operationId: auth/tfa/validate-code
      parameters:
        - in: query
          name: tfaKey
          schema:
            $ref: "#/components/schemas/tfaKey"
          required: true
        - in: query
          name: tfaCode
          schema:
            $ref: "#/components/schemas/tfaCode"
          required: true
      responses:
        "200":
          description: If true the user has correctly scanned the QR and saved a new totp
          content:
            application/json:
              schema:
                type: object
                properties:
                  valid:
                    type: boolean
        "400":
          description: Bad Request
  /auth/logout:
    post:
      tags:
        - auth
      summary: Logs the user out
      description: Unsets the authentication cookie
      operationId: auth/logout
      responses:
        "204":
          description: Logout successful
          headers:
            Set-Cookie:
              schema:
                type: string
                example: "Set-Cookie: shoppingsaver-auth=; Expires=Thu 01 Jan 1970 00:00:00 GMT"
              description: Unsets authentication cookie
  /auth/regenerate-token:
    post:
      tags:
        - auth
      summary: Logs the user out from all devices
      description: Unsets the authentication cookie and invalidates all sessions
      operationId: auth/regenerate-token
      responses:
        "204":
          description: Token regenerated successfully
          headers:
            Set-Cookie:
              schema:
                type: string
                example: "Set-Cookie: shoppingsaver-auth=; Expires=Thu 01 Jan 1970 00:00:00 GMT"
              description: Unsets authentication cookie
        "401":
          description: Unauthorized
  /settings:
    get:
      tags:
        - settings
      summary: Gets the user's settings
      description: Returns an object with all user's settings
      operationId: settings(get)
      responses:
        "200":
          description: User's settings
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    $ref: "#/components/schemas/id"
                  username:
                    $ref: "#/components/schemas/username"
                  email:
                    $ref: "#/components/schemas/email"
                  customization:
                    $ref: "#/components/schemas/customization"
                  sessionExpiration:
                    type: integer
                    example: 1715960830
                  sessionDuration:
                    $ref: "#/components/schemas/sessionDuration"
                  tfa:
                    type: boolean
        "401":
          description: Unauthorized
    patch:
      tags:
        - settings
      summary: Modifies the user's settings
      description: Allows the user to modifies its settings, username, password, ...
      operationId: settings(patch)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  $ref: "#/components/schemas/username"
                email:
                  $ref: "#/components/schemas/email"
                customization:
                  $ref: "#/components/schemas/customization"
                password:
                  $ref: "#/components/schemas/password"
                oldPassword:
                  $ref: "#/components/schemas/password"
                sessionDuration:
                  $ref: "#/components/schemas/sessionDuration"
                tfaKey:
                  oneOf:
                    - $ref: "#/components/schemas/tfaKey"
                    - nullable: true
              required:
                - username
                - email
                - status
                - customization
                - oldPassword
                - sessionDuration
      responses:
        "204":
          description: Settings updated successfully
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: "Forbidden: wrong oldPassword"
  /settings/customization:
    get:
      tags:
        - settings
      summary: Gets the user's customization
      description: Returns an object with user's customization
      operationId: settings/customization
      responses:
        "200":
          description: User's customization
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/customization"
        "401":
          description: Unauthorized
  /categories:
    get:
      tags:
        - categories
      summary: Gets all categories
      description: Returns all categories owned by the user
      operationId: categories(get)
      parameters:
        - in: query
          name: page
          schema:
            $ref: "#/components/schemas/page"
          required: false
        - in: query
          name: order
          schema:
            $ref: "#/components/schemas/order"
          required: false
          example:
            - name: 'asc'
            - defaultLocation:
                name: 'desc'
      responses:
        "200":
          description: All categories of which the user is owner
          content:
            application/json:
              schema:
                type: object
                properties:
                  categories:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          $ref: "#/components/schemas/id"
                        name:
                          $ref: "#/components/schemas/name"
                        defaultLocation:
                          type: object
                          properties:
                            name:
                              $ref: "#/components/schemas/name"
                  pages:
                    $ref: "#/components/schemas/pages"
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
    post:
      tags:
        - categories
      summary: Creates a new category
      description: Creates a new category
      operationId: categories(post)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  $ref: "#/components/schemas/name"
                defaultLocationId:
                  $ref: "#/components/schemas/id"
              required:
                - name
                - defaultLocationId
      responses:
        "201":
          description: Category created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    $ref: "#/components/schemas/id"
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "422":
          description: "Unprocessable Content: category cannot be created"
  /categories/{categoryId}:
    get:
      tags:
        - categories
      summary: Gets category
      description: Returns category's name and defaultLocationId
      operationId: categories/[categoryId](get)
      parameters:
        - in: path
          name: categoryId
          schema:
            $ref: "#/components/schemas/id"
          required: true
      responses:
        "200":
          description: Name and defaultLocationId
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    $ref: "#/components/schemas/name"
                  defaultLocationId:
                    $ref: "#/components/schemas/id"
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: "Forbidden: requesting user does not own requested category"
        "404":
          description: "Not Found: no categories found with specified categoryId"
    patch:
      tags:
        - categories
      summary: Modifies the category
      description: Updates the category's name and defaultLocationId
      operationId: categories/[categoryId](patch)
      parameters:
        - in: path
          name: categoryId
          schema:
            $ref: "#/components/schemas/id"
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  $ref: "#/components/schemas/name"
                defaultLocationId:
                  $ref: "#/components/schemas/id"
              required:
                - name
                - defaultLocationId
      responses:
        "204":
          description: Category updated successfully
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: "Forbidden: requesting user does not own requested category"
        "404":
          description: "Not Found: no categories found with specified categoryId"
        "422":
          description: "Unprocessable Content: category cannot be updated"
  /brands:
    get:
      tags:
        - brands
      summary: Gets all brands
      description: Returns all brands owned by the user
      operationId: brands(get)
      parameters:
        - in: query
          name: page
          schema:
            $ref: "#/components/schemas/page"
          required: false
        - in: query
          name: order
          schema:
            $ref: "#/components/schemas/order"
          required: false
          example:
            - name: 'asc'
            - defaultLocation:
                name: 'desc'
      responses:
        "200":
          description: All brands of which the user is owner
          content:
            application/json:
              schema:
                type: object
                properties:
                  brands:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          $ref: "#/components/schemas/id"
                        name:
                          $ref: "#/components/schemas/name"
                        defaultLocation:
                          type: object
                          properties:
                            name:
                              $ref: "#/components/schemas/name"
                  pages:
                    $ref: "#/components/schemas/pages"
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
    post:
      tags:
        - brands
      summary: Creates a new brand
      description: Creates a new brand
      operationId: brands(post)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  $ref: "#/components/schemas/name"
                defaultLocationId:
                  $ref: "#/components/schemas/id"
              required:
                - name
                - defaultLocationId
      responses:
        "201":
          description: Brand created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    $ref: "#/components/schemas/id"
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "422":
          description: "Unprocessable Content: brand cannot be created"
  /brands/{brandId}:
    get:
      tags:
        - brands
      summary: Gets brand
      description: Returns brand's name and defaultLocationId
      operationId: brands/[brandId](get)
      parameters:
        - in: path
          name: brandId
          schema:
            $ref: "#/components/schemas/id"
          required: true
      responses:
        "200":
          description: Name and defaultLocationId
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    $ref: "#/components/schemas/name"
                  defaultLocationId:
                    $ref: "#/components/schemas/id"
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: "Forbidden: requesting user does not own requested brand"
        "404":
          description: "Not Found: no brands found with specified brandId"
    patch:
      tags:
        - brands
      summary: Modifies the brand
      description: Updates the brand's name and defaultLocationId
      operationId: brands/[brandId](patch)
      parameters:
        - in: path
          name: brandId
          schema:
            $ref: "#/components/schemas/id"
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  $ref: "#/components/schemas/name"
                defaultLocationId:
                  $ref: "#/components/schemas/id"
              required:
                - name
                - defaultLocationId
      responses:
        "204":
          description: Brand updated successfully
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: "Forbidden: requesting user does not own requested brand"
        "404":
          description: "Not Found: no brands found with specified brandId"
        "422":
          description: "Unprocessable Content: brand cannot be updated"
  /supermarkets:
    get:
      tags:
        - supermarkets
      summary: Gets all supermarkets
      description: Returns all supermarkets owned by the user
      operationId: supermarkets(get)
      parameters:
        - in: query
          name: page
          schema:
            $ref: "#/components/schemas/page"
          required: false
        - in: query
          name: order
          schema:
            $ref: "#/components/schemas/order"
          required: false
          example:
            - name: 'asc'
            - defaultLocation:
                name: 'desc'
      responses:
        "200":
          description: All supermarkets of which the user is owner
          content:
            application/json:
              schema:
                type: object
                properties:
                  supermarkets:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          $ref: "#/components/schemas/id"
                        name:
                          $ref: "#/components/schemas/name"
                        defaultLocation:
                          type: object
                          properties:
                            name:
                              $ref: "#/components/schemas/name"
                  pages:
                    $ref: "#/components/schemas/pages"
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
    post:
      tags:
        - supermarkets
      summary: Creates a new supermarket
      description: Creates a new supermarket
      operationId: supermarkets(post)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  $ref: "#/components/schemas/name"
                defaultLocationId:
                  $ref: "#/components/schemas/id"
              required:
                - name
                - defaultLocationId
      responses:
        "201":
          description: Supermarket created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    $ref: "#/components/schemas/id"
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "422":
          description: "Unprocessable Content: supermarket cannot be created"
  /supermarkets/{supermarketId}:
    get:
      tags:
        - supermarkets
      summary: Gets supermarket
      description: Returns supermarket's name and defaultLocationId
      operationId: supermarkets/[supermarketId](get)
      parameters:
        - in: path
          name: supermarketId
          schema:
            $ref: "#/components/schemas/id"
          required: true
      responses:
        "200":
          description: Name and defaultLocationId
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    $ref: "#/components/schemas/name"
                  defaultLocationId:
                    $ref: "#/components/schemas/id"
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: "Forbidden: requesting user does not own requested supermarket"
        "404":
          description: "Not Found: no supermarkets found with specified supermarketId"
    patch:
      tags:
        - supermarkets
      summary: Modifies the supermarket
      description: Updates the supermarket's name and defaultLocationId
      operationId: supermarkets/[supermarketId](patch)
      parameters:
        - in: path
          name: supermarketId
          schema:
            $ref: "#/components/schemas/id"
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  $ref: "#/components/schemas/name"
                defaultLocationId:
                  $ref: "#/components/schemas/id"
              required:
                - name
                - defaultLocationId
      responses:
        "204":
          description: Supermarket updated successfully
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: "Forbidden: requesting user does not own requested supermarket"
        "404":
          description: "Not Found: no supermarkets found with specified supermarketId"
        "422":
          description: "Unprocessable Content: supermarket cannot be updated"
  /products:
    get:
      tags:
        - products
      summary: Gets products using a filter
      description: Returns products owned by the user using a filter
      operationId: products(get)
      parameters:
        - in: query
          name: page
          schema:
            $ref: "#/components/schemas/page"
          required: false
        - in: query
          name: order
          schema:
            $ref: "#/components/schemas/order"
          required: false
          example:
            - name: 'asc'
            - defaultLocation:
                name: 'desc'
        - in: query
          name: filter
          schema:
            $ref: "#/components/schemas/filter"
          required: true
      responses:
        "200":
          description: All filtered products of which the user is owner
          content:
            application/json:
              schema:
                type: object
                properties:
                  products:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          $ref: "#/components/schemas/id"
                        name:
                          $ref: "#/components/schemas/name"
                        category:
                          type: object
                          properties:
                            name:
                              $ref: "#/components/schemas/name"
                        brand:
                          type: object
                          properties:
                            name:
                              $ref: "#/components/schemas/name"
                        quantity:
                          $ref: "#/components/schemas/quantity"
                        itemPrice:
                          $ref: "#/components/schemas/decimal"
                        unitOfMeasurement:
                          $ref: "#/components/schemas/unitOfMeasurement"
                        price:
                          $ref: "#/components/schemas/decimal"
                        supermarket:
                          type: object
                          properties:
                            name:
                              $ref: "#/components/schemas/name"
                  pages:
                    $ref: "#/components/schemas/pages"
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
    post:
      tags:
        - products
      summary: Creates a new product
      description: Creates a new product
      operationId: products(post)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  $ref: "#/components/schemas/name"
                categoryId:
                  $ref: "#/components/schemas/id"
                brandId:
                  $ref: "#/components/schemas/id"
                quantity:
                  $ref: "#/components/schemas/quantity"
                itemPrice:
                  $ref: "#/components/schemas/price"
                unitOfMeasurement:
                  $ref: "#/components/schemas/unitOfMeasurement"
                supermarketId:
                  $ref: "#/components/schemas/id"
              required:
                - name
                - categoryId
                - brandId
                - quantity
                - itemPrice
                - unitOfMeasurement
                - supermarketId
      responses:
        "201":
          description: Product created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    $ref: "#/components/schemas/id"
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "422":
          description: "Unprocessable Content: product cannot be created"
  /products/{productId}:
    get:
      tags:
        - products
      summary: Gets product
      description: Returns most product attributes
      operationId: products/[productId](get)
      parameters:
        - in: path
          name: productId
          schema:
            $ref: "#/components/schemas/id"
          required: true
      responses:
        "200":
          description: Most product attributes
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    $ref: "#/components/schemas/name"
                  categoryId:
                    $ref: "#/components/schemas/id"
                  brandId:
                    $ref: "#/components/schemas/id"
                  quantity:
                    $ref: "#/components/schemas/quantity"
                  itemPrice:
                    $ref: "#/components/schemas/price"
                  unitOfMeasurement:
                    $ref: "#/components/schemas/unitOfMeasurement"
                  supermarketId:
                    $ref: "#/components/schemas/id"
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: "Forbidden: requesting user does not own requested product"
        "404":
          description: "Not Found: no products found with specified productId"
    patch:
      tags:
        - products
      summary: Modifies the product
      description: Updates the products's name and most of its attributes
      operationId: products/[productId](patch)
      parameters:
        - in: path
          name: productId
          schema:
            $ref: "#/components/schemas/id"
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  $ref: "#/components/schemas/name"
                categoryId:
                  $ref: "#/components/schemas/id"
                brandId:
                  $ref: "#/components/schemas/id"
                quantity:
                  $ref: "#/components/schemas/quantity"
                itemPrice:
                  $ref: "#/components/schemas/price"
                unitOfMeasurement:
                  $ref: "#/components/schemas/unitOfMeasurement"
                supermarketId:
                  $ref: "#/components/schemas/id"
              required:
                - name
                - categoryId
                - brandId
                - quantity
                - itemPrice
                - unitOfMeasurement
                - supermarketId
      responses:
        "204":
          description: Product updated successfully
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: "Forbidden: requesting user does not own requested product"
        "404":
          description: "Not Found: no products found with specified productId"
        "422":
          description: "Unprocessable Content: product cannot be updated"
    delete:
      tags:
        - products
      summary: Deletes product
      description: Removes the product
      operationId: products/[productId](delete)
      parameters:
        - in: path
          name: productId
          schema:
            $ref: "#/components/schemas/id"
          required: true
      responses:
        "204":
          description: Product deleted successfully
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: "Forbidden: requesting user does not own requested product"
        "404":
          description: "Not Found: no products found with specified productId"